### ISSUE TITLE
File name conflicts

### ISSUE THREAD

**Issue by TMUND** [foundryinteractive/foundry-interactive#15]
We currently have `Clients.js` and `Clients.jsx` files in the same `/clients` folder. This is causing issues when we import `Clients`. We should rename the `Clients.js` to something like `clientData.js`. 

The same is true for `Services.js` in the `/services` folder.

**Comment by toalina** [comment]
Question: Why is Services.js and Profiles.js (and so on) capitalized?

**Comment by TMUND** [comment]
@toalina This was just me naming stuff as I was going along with giving it much thought. `services.js` is better in this case.
